### ISSUE TITLE
 不能直接vue2使用

### ISSUE THREAD

**Issue by xianzhiyun** [likaia/screen-shot#1]
![image](https://user-images.githubusercontent.com/23547626/106736250-2dfe7600-6650-11eb-8233-4238ab6525f9.png)

**Comment by likaia** [comment]
收到，我尽快解决。

**Comment by xianzhiyun** [comment]
解决了，记得回复一下，期待

**Comment by likaia** [comment]
嗯嗯 好

**Comment by likaia** [comment]
我用原生js重构了这个插件，支持所有js平台的设备，vue2版本的请移步：web端自定义截屏插件(原生JS版)：https://www.npmjs.com/package/js-web-screen-shot

**Comment by xianzhiyun** [comment]
厉害了大佬，这么晚还在解决问题

**Comment by likaia** [comment]
害

**Comment by 15687125332** [comment]
![image](https://user-images.githubusercontent.com/93255985/139044892-b45edd05-010e-4429-ad68-bdfa3ca67b77.png)
您好老师，我想请问一下，中间我是使用iframe，iframe中使用您的插件。不知道为什么截屏，只会显示在iframe区域，有什么办法可以让它的范围变成整个屏幕

**Comment by likaia** [comment]
用webrtc模式试试
