### ISSUE TITLE
添加截图失败的回调方法

### ISSUE THREAD

**Issue by oo10** [likaia/screen-shot#15]
当浏览器不支持webrtc或者使用了非HTTPS的时候，截图时会抛异常，希望组件能添加一个异常 @error 的回调，使得业务场景下能捕获到异常。

谢谢！ 

<screen-short v-if="screenshotStatus"
  @destroy-component="destroyComponent"
  @get-image-data="getImg"
  @error="getError"
></screen-short>

**Comment by likaia** [comment]
行，我晚些时候加一下

**Comment by likaia** [comment]
> 当浏览器不支持webrtc或者使用了非HTTPS的时候，截图时会抛异常，希望组件能添加一个异常 @error 的回调，使得业务场景下能捕获到异常。
> 
> 谢谢！
> 
> <screen-short v-if="screenshotStatus" @destroy-component="destroyComponent" @get-image-data="getImg" @error="getError"
> 
> >

加好了，更新到1.5.3即可
