### ISSUE TITLE
希望添加对输入文字的处理

### ISSUE THREAD

**Issue by HhfGzy** [likaia/screen-shot#18]
输入文字时可选择字体大小及字体颜色

**Comment by likaia** [comment]
可以，有时间我加一下

**Comment by HhfGzy** [comment]
js的版本也可以加一下，之前我们项目中需要使用到就对版本改过一次，那你修改后我们正好就不用改了

**Comment by likaia** [comment]
> 输入文字时可选择字体大小及字体颜色

这个加到js版本上去了，vue版本还没时间加
