### ISSUE TITLE
截屏工具栏显示不全，截图有点小问题

### ISSUE THREAD

**Issue by meimosor** [likaia/screen-shot#3]
截屏工具栏显示不全，截图有点小问题：截图空白，下面是QQ截图的对比

QQ截图：
![QQ截图20210513154132](https://user-images.githubusercontent.com/31975932/118094991-14fd2200-b402-11eb-87d6-26112d13ddcb.png)

实际截图：
![2021-05-13_154203](https://user-images.githubusercontent.com/31975932/118095018-22b2a780-b402-11eb-94f3-f630ba4c5091.png)

**Comment by likaia** [comment]
样式冲突了吧，你检查下
