### ISSUE TITLE
Firefox 截图响应很慢

### ISSUE THREAD

**Issue by cgrain1998** [likaia/screen-shot#5]
项目 Vue3 +ts

main.ts 
导入
```
// 导入截屏插件
import screenShort from "vue-web-screen-shot"; 

// 使用截屏插件
app.use(screenShort, { enableWebRtc: false,clickCutFullScreen :true,level:1000 ,hiddenToolIco:{text :true }})
```
火狐
![image](https://user-images.githubusercontent.com/35121432/147194799-b5f80642-2cc9-472d-b639-2098ed807eb8.png)

谷歌
![image](https://user-images.githubusercontent.com/35121432/147194852-18d67556-6927-4a5a-8a9f-0c0183c6da99.png)

请问如何处理呢，差距太大了

**Comment by likaia** [comment]
当页面图片资源过多时，就会导致这个问题的出现

**Comment by cgrain1998** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by cgrain1998** [comment]
> 当页面图片过多的时候，会发现这个资源问题的出现

thx!
