### ISSUE TITLE
使用 Html2canvas 方式截图，截图图片中，网络图片渲染为空白

### ISSUE THREAD

**Issue by Stephen-liangz** [likaia/screen-shot#8]
如果直接使用 Html2canvas 截图，图片显示是正常的。

红框为网络图片、绿框为本地图片。
![download](https://user-images.githubusercontent.com/13581271/163949509-ff1b4366-b3f3-41c2-89c7-5c727e3e5bae.png)

**Comment by Stephen-liangz** [comment]
EventMonitoring.ts 中 html2canvas 截屏操作，打开跨域选项可以解决，不过我 patch-package 一直无效。作者看到了麻烦修改一下。
html2canvas(document.body, {})
修改为
html2canvas(document.body, {useCORS: true, allowTaint: true})

**Comment by likaia** [comment]
已修复，插件更新至1.3.3即可，具体的使用方法请看文档。
<img width="640" alt="image" src="https://user-images.githubusercontent.com/35120858/164237815-10fadf69-dc77-49c5-b598-92e4a2d86f5f.png">
